---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv
  namespace: project-fix
spec:
  storageClassName: ""
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /mnt/project/
    server: 192.168.0.107
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-2
  namespace: project-fix
spec:
  storageClassName: ""
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /mnt/project2/
    server: 192.168.0.107
---
