apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume2
  namespace: default
  labels:
    type: local
spec:
  storageClassName: ""
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data2"

